Repository KristinJJ/Cranidores, pull requests merged in 2023-05, with the labels that each got.

#54 pushing Dashboards folder and dummy Tableau dashboard for StateDemogr…
  Tableau/Dashboards/StateDemo22MapDashboard.twb
Labels: Week 2

#73 Skeleton ReadMe
  README.md
Labels: Week 6

#78 PreFinalDraft README.md
  README.md
Labels: Week 6

#81 Added 2022 scorecard data prep files.
  Data/2022_excel/2022_Scorecard_Cranidores_Merge.xlsx
  Tableau/PrepBuilder/Cranidores_2022.tfl
Labels: enhancement

#83 Final Draft - Round 1
  README.md
Labels: Week 6

#84 week6 workbook backup
  Tableau/Workbooks/HighSchoolComputerScienceAccessibilityandPassRate.twbx
Labels: documentation, Week 6

#87 Last Minute README.md update
  README.md
Labels: Week 6, Week 7
