Repository KristinJJ/Cranidores, pull requests merged in 2023-04, with the labels that each got.

#2 Issue #1 - Add name to Readme
  README.md
Labels: documentation

#35 Issue #28 Add Tableau folder and Packaged Workbook
  Tableau/.gitignore
  Tableau/Workbooks/.~Cranidores__16030.twbr
  Tableau/Workbooks/Cranidores.twbx
Labels: enhancement, Week 2

#34 removed empty zip folder
  csv_files
Labels: Week 2

#53 Update ReadMe with team and role
  README.md
Labels: Week 2

#55 Issue #29 - uploading raw files 2021 and 2022
  Data/2021_csv/StudentComparisonMetrics.csv
  Data/2021_excel/2021_State_of_CS_data.xlsx
  Data/2021_excel/2021_State_of_CS_data_LocationIncome.xlsx
  Data/2021_excel/2021_State_of_CS_data_LocationIncome2.xlsx
  Data/2021_excel/APCSDetailedData3.xlsx
  Data/2021_excel/APCSDetailedData3Working.xlsx
  Data/2021_excel/CSA-2010-2021-By-State.xlsx
  Data/2021_excel/CSP-2017-2021-By-State.xlsx
  Data/2021_excel/StatePoliciesWithDemographic2.xlsx
  Data/2022_csv/APCSA-2021-Data.csv
  Data/2022_csv/APCSP-2021-Data.csv
  Data/2022_csv/APCSbyStateFor2022.csv
  Data/2022_excel/2022_state_of_cs_data.xlsx
  Data/2022_excel/APCS-2021-All.xlsx
  Data/2022_excel/SchoolBasedDataFinal2022.xlsx
  Data/2022_excel/StateDemographics2022a.xlsx
  Data/2022_excel/StudentKeyMetricsfor2022.xlsx
Labels: Week 2
